services:
  galera1:
    image: slurm-db
    build:
      context: ./
      dockerfile: ./container/db/Dockerfile
    command: ["new_cluster"]
    hostname: galera1
    container_name: galera1
    expose:
      - "3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      # need to be consistent with slurmdbd.conf
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql1:/var/lib/mysql
    networks:
      - slurm-network

  galera2:
    image: slurm-db
    hostname: galera2
    container_name: galera2
    command: ["add_cluster"]
    expose:
      - "3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql2:/var/lib/mysql
    networks:
      - slurm-network
    depends_on:
      - "galera1"

  galera3:
    image: slurm-db
    hostname: galera3
    container_name: galera3
    command: ["add_cluster"]
    expose:
      - "3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql3:/var/lib/mysql
    networks:
      - slurm-network
    depends_on:
      - "galera1"

  dbproxy:
    image: dbproxy
    build:
      context: ./
      dockerfile: ./container/haproxy/Dockerfile
    container_name: dbproxy
    hostname: dbproxy
    expose:
      - "3306"
    depends_on:
      - "galera1"
      - "galera2"
      - "galera3"
    networks:
      - slurm-network

  slurmdbd:
    image: slurm-debian
    build:
      context: ./
      dockerfile: ./container/slurm/Dockerfile
      args:
        SLURM_TAG: ${SLURM_TAG}
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - "dbproxy"
    networks:
      - slurm-network

  slurmctld:
    image: slurm-debian
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"
    networks:
      - slurm-network

  slurmrestd:
    image: slurm-debian
    cap_add:
      - SYS_ADMIN
    command: ["slurmrestd"]
    container_name: slurmrestd
    hostname: slurmrestd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6820"
    depends_on:
      - "slurmctld"
    networks:
      - slurm-network

  cmpt1:
    image: slurm-debian
    command: ["slurmd"]
    hostname: cmpt1
    container_name: cmpt1
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    networks:
      - slurm-network

  cmpt2:
    image: slurm-debian
    command: ["slurmd"]
    hostname: cmpt2
    container_name: cmpt2
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    networks:
      - slurm-network

volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql1:
  var_lib_mysql2:
  var_lib_mysql3:
  var_log_slurm:

networks:
  slurm-network:
    driver: bridge
